# Generated by Django 6.0.3 on 2026-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_admin', '0004_add_username_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_reviewed',
            field=models.BooleanField(default=True),
        ),
    ]
